export interface AllergyOption {
  id: string;
  name: string;
  category: "MEDICAMENTO" | "ALIMENTO" | "AMBIENTAL" | "OTRO";
}

export const COMMON_ALLERGIES: AllergyOption[] = [
  // --- MEDICAMENTOS ---
  { id: "m1", name: "Penicilina", category: "MEDICAMENTO" },
  { id: "m2", name: "Amoxicilina", category: "MEDICAMENTO" },
  { id: "m3", name: "Ampicilina", category: "MEDICAMENTO" },
  { id: "m4", name: "Aspirina (Ácido Acetilsalicílico)", category: "MEDICAMENTO" },
  { id: "m5", name: "Ibuprofeno", category: "MEDICAMENTO" },
  { id: "m6", name: "Naproxeno", category: "MEDICAMENTO" },
  { id: "m7", name: "Diclofenaco", category: "MEDICAMENTO" },
  { id: "m8", name: "Ketorolaco", category: "MEDICAMENTO" },
  { id: "m9", name: "Metamizol (Dipirona)", category: "MEDICAMENTO" },
  { id: "m10", name: "Sulfonamidas (Trimetoprima/Sulfametoxazol)", category: "MEDICAMENTO" },
  { id: "m11", name: "Ciprofloxacino", category: "MEDICAMENTO" },
  { id: "m12", name: "Ceftriaxona", category: "MEDICAMENTO" },
  { id: "m13", name: "Insulina", category: "MEDICAMENTO" },
  { id: "m14", name: "Medios de contraste yodados", category: "MEDICAMENTO" },
  { id: "m15", name: "Anestésicos locales (Lidocaína)", category: "MEDICAMENTO" },
  { id: "m16", name: "Cefalexina", category: "MEDICAMENTO" },
  { id: "m17", name: "Cefuroxima", category: "MEDICAMENTO" },
  { id: "m18", name: "Cefotaxima", category: "MEDICAMENTO" },
  { id: "m19", name: "Clindamicina", category: "MEDICAMENTO" },
  { id: "m20", name: "Eritromicina", category: "MEDICAMENTO" },
  { id: "m21", name: "Claritromicina", category: "MEDICAMENTO" },
  { id: "m22", name: "Azitromicina", category: "MEDICAMENTO" },
  { id: "m23", name: "Levofloxacino", category: "MEDICAMENTO" },
  { id: "m24", name: "Moxifloxacino", category: "MEDICAMENTO" },
  { id: "m25", name: "Vancomicina", category: "MEDICAMENTO" },
  { id: "m26", name: "Carbamazepina", category: "MEDICAMENTO" },
  { id: "m27", name: "Fenitoína", category: "MEDICAMENTO" },
  { id: "m28", name: "Ácido valproico", category: "MEDICAMENTO" },
  { id: "m29", name: "Lamotrigina", category: "MEDICAMENTO" },
  { id: "m30", name: "Morfina", category: "MEDICAMENTO" },
  { id: "m31", name: "Codeína", category: "MEDICAMENTO" },
  { id: "m32", name: "Tramadol", category: "MEDICAMENTO" },
  { id: "m33", name: "Fentanilo", category: "MEDICAMENTO" },
  { id: "m34", name: "Paracetamol (Acetaminofén)", category: "MEDICAMENTO" },
  { id: "m35", name: "Meloxicam", category: "MEDICAMENTO" },
  { id: "m36", name: "Celecoxib", category: "MEDICAMENTO" },
  { id: "m37", name: "Indometacina", category: "MEDICAMENTO" },
  { id: "m38", name: "Enalapril", category: "MEDICAMENTO" },
  { id: "m39", name: "Losartán", category: "MEDICAMENTO" },
  { id: "m40", name: "Captopril", category: "MEDICAMENTO" },
  { id: "m41", name: "Metformina", category: "MEDICAMENTO" },
  { id: "m42", name: "Glibenclamida", category: "MEDICAMENTO" },
  { id: "m43", name: "Heparina", category: "MEDICAMENTO" },
  { id: "m44", name: "Warfarina", category: "MEDICAMENTO" },
  { id: "m45", name: "Omeprazol", category: "MEDICAMENTO" },
  { id: "m46", name: "Ranitidina", category: "MEDICAMENTO" },
  { id: "m47", name: "Prednisona", category: "MEDICAMENTO" },
  { id: "m48", name: "Dexametasona", category: "MEDICAMENTO" },
  { id: "m49", name: "Hidrocortisona", category: "MEDICAMENTO" },
  { id: "m50", name: "Propofol", category: "MEDICAMENTO" },
  { id: "m51", name: "Midazolam", category: "MEDICAMENTO" },
  { id: "m52", name: "Amiodarona", category: "MEDICAMENTO" },
  { id: "m53", name: "Interferón", category: "MEDICAMENTO" },
  { id: "m54", name: "Infliximab", category: "MEDICAMENTO" },
  { id: "m55", name: "Adalimumab", category: "MEDICAMENTO" },
  { id: "m56", name: "Vacuna antigripal", category: "MEDICAMENTO" },
  { id: "m57", name: "Vacuna COVID-19", category: "MEDICAMENTO" },

  // --- ALIMENTOS ---
  { id: "a1", name: "Leche de vaca / Lactosa", category: "ALIMENTO" },
  { id: "a2", name: "Huevo (Clara)", category: "ALIMENTO" },
  { id: "a3", name: "Huevo (Yema)", category: "ALIMENTO" },
  { id: "a4", name: "Cacahuates (Maní)", category: "ALIMENTO" },
  { id: "a5", name: "Nueces de árbol (Almendra, Cashew, Pistache)", category: "ALIMENTO" },
  { id: "a6", name: "Camarones / Mariscos", category: "ALIMENTO" },
  { id: "a7", name: "Pescado", category: "ALIMENTO" },
  { id: "a8", name: "Trigo (Gluten)", category: "ALIMENTO" },
  { id: "a9", name: "Soya", category: "ALIMENTO" },
  { id: "a10", name: "Fresa", category: "ALIMENTO" },
  { id: "a11", name: "Chocolate / Cacao", category: "ALIMENTO" },
  { id: "a12", name: "Piñones", category: "ALIMENTO" },
  { id: "a13", name: "Kiwi", category: "ALIMENTO" },
  { id: "a14", name: "Legumbres (Lentejas, Frijoles)", category: "ALIMENTO" },
  { id: "a15", name: "Durazno", category: "ALIMENTO" },
  { id: "a16", name: "Manzana", category: "ALIMENTO" },
  { id: "a17", name: "Pera", category: "ALIMENTO" },
  { id: "a18", name: "Plátano", category: "ALIMENTO" },
  { id: "a19", name: "Mango", category: "ALIMENTO" },
  { id: "a20", name: "Papaya", category: "ALIMENTO" },
  { id: "a21", name: "Piña", category: "ALIMENTO" },
  { id: "a22", name: "Melón", category: "ALIMENTO" },
  { id: "a23", name: "Sandía", category: "ALIMENTO" },
  { id: "a24", name: "Uvas", category: "ALIMENTO" },
  { id: "a25", name: "Aguacate", category: "ALIMENTO" },
  { id: "a26", name: "Tomate", category: "ALIMENTO" },
  { id: "a27", name: "Zanahoria", category: "ALIMENTO" },
  { id: "a28", name: "Apio", category: "ALIMENTO" },
  { id: "a29", name: "Pepino", category: "ALIMENTO" },
  { id: "a30", name: "Maíz", category: "ALIMENTO" },
  { id: "a31", name: "Arroz", category: "ALIMENTO" },
  { id: "a32", name: "Avena", category: "ALIMENTO" },
  { id: "a33", name: "Cebada", category: "ALIMENTO" },
  { id: "a34", name: "Centeno", category: "ALIMENTO" },
  { id: "a35", name: "Ajonjolí (Sésamo)", category: "ALIMENTO" },
  { id: "a36", name: "Semillas de girasol", category: "ALIMENTO" },
  { id: "a37", name: "Semillas de chía", category: "ALIMENTO" },
  { id: "a38", name: "Linaza", category: "ALIMENTO" },
  { id: "a39", name: "Carne de res", category: "ALIMENTO" },
  { id: "a40", name: "Carne de cerdo", category: "ALIMENTO" },
  { id: "a41", name: "Carne de pollo", category: "ALIMENTO" },
  { id: "a42", name: "Carne de pavo", category: "ALIMENTO" },
  { id: "a43", name: "Atún", category: "ALIMENTO" },
  { id: "a44", name: "Salmón", category: "ALIMENTO" },
  { id: "a45", name: "Quesos maduros", category: "ALIMENTO" },
  { id: "a46", name: "Yogurt", category: "ALIMENTO" },
  { id: "a47", name: "Miel", category: "ALIMENTO" },
  { id: "a48", name: "Mostaza", category: "ALIMENTO" },
  { id: "a49", name: "Colorantes artificiales", category: "ALIMENTO" },
  { id: "a50", name: "Conservadores (Sulfitos)", category: "ALIMENTO" },
  { id: "a51", name: "Edulcorantes artificiales", category: "ALIMENTO" },
  { id: "a52", name: "Glutamato monosódico (MSG)", category: "ALIMENTO" },
  { id: "a53", name: "Maracuyá", category: "ALIMENTO" },
  { id: "a54", name: "Guayaba", category: "ALIMENTO" },

  // --- AMBIENTALES ---
  { id: "e1", name: "Polen de flores", category: "AMBIENTAL" },
  { id: "e2", name: "Ácaros del polvo", category: "AMBIENTAL" },
  { id: "e3", name: "Pelo de gato", category: "AMBIENTAL" },
  { id: "e4", name: "Pelo de perro", category: "AMBIENTAL" },
  { id: "e5", name: "Humedad / Moho", category: "AMBIENTAL" },
  { id: "e6", name: "Pasto / Césped", category: "AMBIENTAL" },
  { id: "e7", name: "Cucaracha (Desechos)", category: "AMBIENTAL" },
  { id: "e8", name: "Árboles (Polen)", category: "AMBIENTAL" },
  { id: "e9", name: "Malezas (Polen)", category: "AMBIENTAL" },
  { id: "e10", name: "Hongos ambientales", category: "AMBIENTAL" },
  { id: "e11", name: "Esporas de moho", category: "AMBIENTAL" },
  { id: "e12", name: "Plumas", category: "AMBIENTAL" },
  { id: "e13", name: "Caspa de animales", category: "AMBIENTAL" },
  { id: "e14", name: "Caballos", category: "AMBIENTAL" },
  { id: "e15", name: "Conejos", category: "AMBIENTAL" },
  { id: "e16", name: "Perfumes / Fragancias", category: "AMBIENTAL" },
  { id: "e17", name: "Productos de limpieza", category: "AMBIENTAL" },
  { id: "e18", name: "Cloro", category: "AMBIENTAL" },
  { id: "e19", name: "Detergentes", category: "AMBIENTAL" },
  { id: "e20", name: "Suavizantes de telas", category: "AMBIENTAL" },
  { id: "e21", name: "Humo de cigarro", category: "AMBIENTAL" },
  { id: "e22", name: "Humo de leña", category: "AMBIENTAL" },
  { id: "e23", name: "Contaminación ambiental", category: "AMBIENTAL" },
  { id: "e24", name: "Látex", category: "AMBIENTAL" },
  { id: "e25", name: "Picaduras de insectos", category: "AMBIENTAL" },
  { id: "e26", name: "Abejas", category: "AMBIENTAL" },
  { id: "e27", name: "Avispas", category: "AMBIENTAL" },

  // --- OTROS ---
  { id: "o1", name: "Látex", category: "OTRO" },
  { id: "o2", name: "Picadura de abeja", category: "OTRO" },
  { id: "o3", name: "Picadura de avispa", category: "OTRO" },
  { id: "o4", name: "Níquel (Joyería/Relojes)", category: "OTRO" },
  { id: "o5", name: "Fragancias / Perfumes", category: "OTRO" },
  { id: "o6", name: "Detergentes / Jabones", category: "OTRO" },
  { id: "o7", name: "Cintas adhesivas / Esparadrapo", category: "OTRO" },
  { id: "o8", name: "Cobalto", category: "OTRO" },
  { id: "o9", name: "Cromo", category: "OTRO" },
  { id: "o10", name: "Formaldehído", category: "OTRO" },
  { id: "o11", name: "Parabenos (Cosméticos)", category: "OTRO" },
  { id: "o12", name: "Tintes para cabello", category: "OTRO" },
  { id: "o13", name: "Henna negra", category: "OTRO" },
  { id: "o14", name: "Maquillaje", category: "OTRO" },
  { id: "o15", name: "Protector solar", category: "OTRO" },
  { id: "o16", name: "Gel antibacterial", category: "OTRO" },
  { id: "o17", name: "Alcohol (uso tópico)", category: "OTRO" },
  { id: "o18", name: "Yodo tópico", category: "OTRO" },
  { id: "o19", name: "Clorhexidina", category: "OTRO" },
  { id: "o20", name: "Antisépticos tópicos", category: "OTRO" },
  { id: "o21", name: "Guantes de látex", category: "OTRO" },
  { id: "o22", name: "Silicona", category: "OTRO" },
  { id: "o23", name: "Prótesis dentales (Materiales)", category: "OTRO" },
  { id: "o24", name: "Resinas dentales", category: "OTRO" },
  { id: "o25", name: "Plásticos", category: "OTRO" },
  { id: "o26", name: "Resinas industriales", category: "OTRO" },
  { id: "o27", name: "Cemento", category: "OTRO" },

  { id: "o28", name: "Alergia no especificada", category: "OTRO" },
  { id: "o29", name: "Alergia desconocida", category: "OTRO" },
  { id: "o30", name: "Otra alergia (especificar)", category: "OTRO" },
];

export const searchAllergies = (query: string) => {
  const cleanQuery = query
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

  return COMMON_ALLERGIES.filter((allergy) => {
    const cleanName = allergy.name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
    return cleanName.includes(cleanQuery);
  });
};
